/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CommandToRun = string;
export type GlobMatchBasedOnMinimatch = string;

export interface TrompConfig {
  commands: Commands[];
  [k: string]: any;
}
export interface Commands {
  command: CommandToRun;
  match: GlobMatchBasedOnMinimatch;
  [k: string]: any;
}
