name: Client Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0
          sudo cp src/test/xvfb.init /etc/init.d/xvfb
          sudo chmod +x /etc/init.d/xvfb
          sudo update-rc.d xvfb defaults
          sudo service xvfb start
      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key:
            ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}',
            github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install deps and compile ts
        run: |
          yarn --frozen-lockfile
          yarn run compile
        env:
          CI: true
      - run: yarn format-check
      - run: yarn test-unit
      - run: DISPLAY=:10 yarn test
